### ISSUE TITLE
Photos Widget - User Profile Page

### ISSUE THREAD

**Issue by NTanzeel** [NTanzeel/Fidelis#7]
**UI**
- Nicer widget design, ensure the photos are laid out nicely in a grid inside the widget.
- A UI for viewing the photos.

**Functionality**
- Load all undeleted photos, order of date posted descending. Should see the most recent in the widget.
- Need a way to enlarge a photo, potentially a model?
- Need a way to go through all photos ever... Potentially a next and previous arrow on the modal to keep going through photos or even a page with all the photos.

**Comment by NTanzeel** [comment]
Why was this reopened @Jordan8295? What's the issue?

**Comment by Jordan8295** [comment]
I had marked it as done without testing it, but it's all good
